# Generated by Django 6.0.3 on 2026-04-14 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_sample_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietphieukiemke',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chitietphieunhap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chitietphieuxuat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doituongnhan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='vai_tro',
            field=models.CharField(choices=[('Admin', 'Chủ cửa hàng'), ('NhanVien', 'Nhân viên kho'), ('GiaoHang', 'Giao hàng')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phieukiemke',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phieunhap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phieuxuat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tonkho',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='LichSuDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai', models.CharField(choices=[('tao_don', 'Tạo đơn hàng'), ('xuat_kho', 'Xuất kho'), ('dang_giao', 'Đang giao hàng'), ('thanh_cong', 'Giao hàng thành công')], max_length=20)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('phieu_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su', to='suppliers.phieuxuat')),
            ],
            options={
                'ordering': ['-thoi_gian'],
            },
        ),
    ]
