# Generated by Django 6.0.3 on 2026-04-14 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_chitietphieukiemke_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LichSuDonHang',
        ),
    ]
