# Generated by Django 6.0.3 on 2026-04-14 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_delete_lichsudonhang'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichSuDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai', models.CharField(choices=[('tao_don', 'Tạo đơn hàng'), ('xuat_kho', 'Xuất kho'), ('dang_giao', 'Đang giao hàng'), ('thanh_cong', 'Giao hàng thành công')], max_length=20)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('phieu_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su', to='suppliers.phieuxuat')),
            ],
            options={
                'ordering': ['-thoi_gian'],
            },
        ),
    ]
