# Generated by Django 6.0.3 on 2026-04-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_lichsudonhang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='ma_son',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
