# Generated by Django 6.0.3 on 2026-04-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_alter_sanpham_ma_son'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='ty_le_loi_nhuan',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='gia_ban',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
