# Generated by Django 6.0.3 on 2026-04-14 11:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_sanpham_ty_le_loi_nhuan_alter_sanpham_gia_ban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='han_su_dung',
        ),
        migrations.AddField(
            model_name='chitietphieunhap',
            name='han_su_dung',
            field=models.DateField(default=datetime.date(2026, 4, 14)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chitietphieunhap',
            name='ma_lo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='chitietphieukiemke',
            name='chenh_lech',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='chitietphieunhap',
            name='phieu_nhap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='suppliers.phieunhap'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='gia_ban',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
    ]
