# Generated by Django 6.0 on 2026-04-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietDonDatHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField()),
                ('don_gia', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('thanh_tien', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='DonDatHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_don', models.CharField(max_length=50, unique=True)),
                ('ngay_dat', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('trang_thai', models.CharField(choices=[('Chờ xử lý', 'Chờ xử lý'), ('Đã xuất 1 phần', 'Đã xuất 1 phần'), ('Đã xuất', 'Đã xuất'), ('Đã hủy', 'Đã hủy')], default='Chờ xử lý', max_length=50)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
