# Generated by Django 6.0 on 2026-04-14 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Export', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietdondathang',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.sanpham'),
        ),
        migrations.AddField(
            model_name='dondathang',
            name='doi_tuong_nhan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suppliers.doituongnhan'),
        ),
        migrations.AddField(
            model_name='chitietdondathang',
            name='don_dat_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Export.dondathang'),
        ),
    ]
