# Generated by Django 4.2.8 on 2026-04-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_sample_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='vai_tro',
            field=models.CharField(choices=[('Admin', 'Chủ cửa hàng'), ('NhanVien', 'Nhân viên kho'), ('GiaoHang', 'Giao hàng')], max_length=50),
        ),
    ]
